// Code generated by qtc from "mail.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line mail.qtpl:1
package mailtpl

// Mail templates are compiled by quicktemplate. Keep product copy here instead of
// building email bodies in handlers.
//
// Generate with:
//   go run github.com/valyala/quicktemplate/qtc@v1.8.0 -dir=internal/server/mailtpl
//

//line mail.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line mail.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line mail.qtpl:9
func StreamMagicLinkText(qw422016 *qt422016.Writer, d MagicLinkData) {
//line mail.qtpl:9
	qw422016.N().S(d.Intro)
//line mail.qtpl:9
	qw422016.N().S(`

`)
//line mail.qtpl:11
	qw422016.N().S(d.Link)
//line mail.qtpl:11
	qw422016.N().S(`

`)
//line mail.qtpl:13
	qw422016.N().S(d.ExpiresLabel)
//line mail.qtpl:13
	qw422016.N().S(`: `)
//line mail.qtpl:13
	qw422016.N().S(d.ExpiresAt)
//line mail.qtpl:13
	qw422016.N().S(`
`)
//line mail.qtpl:14
	qw422016.N().S(d.Footnote)
//line mail.qtpl:14
	qw422016.N().S(`
`)
//line mail.qtpl:15
}

//line mail.qtpl:15
func WriteMagicLinkText(qq422016 qtio422016.Writer, d MagicLinkData) {
//line mail.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mail.qtpl:15
	StreamMagicLinkText(qw422016, d)
//line mail.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line mail.qtpl:15
}

//line mail.qtpl:15
func MagicLinkText(d MagicLinkData) string {
//line mail.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line mail.qtpl:15
	WriteMagicLinkText(qb422016, d)
//line mail.qtpl:15
	qs422016 := string(qb422016.B)
//line mail.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line mail.qtpl:15
	return qs422016
//line mail.qtpl:15
}

//line mail.qtpl:17
func StreamMagicLinkHTML(qw422016 *qt422016.Writer, d MagicLinkData) {
//line mail.qtpl:17
	qw422016.N().S(`<!doctype html>
<html>
<body style="margin:0;padding:0;background:#f6f7fb;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">
  <div style="max-width:560px;margin:0 auto;padding:32px 20px;">
    <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;padding:28px;">
      <div style="font-size:13px;font-weight:700;color:#2563eb;margin-bottom:12px;">`)
//line mail.qtpl:22
	qw422016.E().S(d.AppName)
//line mail.qtpl:22
	qw422016.N().S(`</div>
      <h1 style="font-size:22px;line-height:1.3;margin:0 0 14px;color:#111827;">`)
//line mail.qtpl:23
	qw422016.E().S(d.Title)
//line mail.qtpl:23
	qw422016.N().S(`</h1>
      <p style="font-size:15px;line-height:1.7;margin:0 0 22px;color:#4b5563;">`)
//line mail.qtpl:24
	qw422016.E().S(d.Footnote)
//line mail.qtpl:24
	qw422016.N().S(`</p>
      <p style="margin:0 0 22px;"><a href="`)
//line mail.qtpl:25
	qw422016.E().S(d.Link)
//line mail.qtpl:25
	qw422016.N().S(`" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;border-radius:6px;padding:12px 18px;font-weight:700;">`)
//line mail.qtpl:25
	qw422016.E().S(d.ButtonText)
//line mail.qtpl:25
	qw422016.N().S(`</a></p>
      <p style="font-size:13px;line-height:1.7;margin:0 0 8px;color:#6b7280;">`)
//line mail.qtpl:26
	qw422016.E().S(d.ExpiresLabel)
//line mail.qtpl:26
	qw422016.N().S(`: `)
//line mail.qtpl:26
	qw422016.E().S(d.ExpiresAt)
//line mail.qtpl:26
	qw422016.N().S(`</p>
      <p style="font-size:12px;line-height:1.7;margin:0;color:#6b7280;word-break:break-all;">`)
//line mail.qtpl:27
	qw422016.E().S(d.Link)
//line mail.qtpl:27
	qw422016.N().S(`</p>
    </div>
  </div>
</body>
</html>
`)
//line mail.qtpl:32
}

//line mail.qtpl:32
func WriteMagicLinkHTML(qq422016 qtio422016.Writer, d MagicLinkData) {
//line mail.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mail.qtpl:32
	StreamMagicLinkHTML(qw422016, d)
//line mail.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line mail.qtpl:32
}

//line mail.qtpl:32
func MagicLinkHTML(d MagicLinkData) string {
//line mail.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line mail.qtpl:32
	WriteMagicLinkHTML(qb422016, d)
//line mail.qtpl:32
	qs422016 := string(qb422016.B)
//line mail.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line mail.qtpl:32
	return qs422016
//line mail.qtpl:32
}

//line mail.qtpl:34
func StreamApprovalText(qw422016 *qt422016.Writer, d ApprovalData) {
//line mail.qtpl:34
	qw422016.N().S(d.Greeting)
//line mail.qtpl:34
	qw422016.N().S(`

`)
//line mail.qtpl:36
	qw422016.N().S(d.Intro)
//line mail.qtpl:36
	qw422016.N().S(`

`)
//line mail.qtpl:38
	for _, row := range d.Rows {
//line mail.qtpl:38
		qw422016.N().S(`
`)
//line mail.qtpl:39
		if row.Value != "" {
//line mail.qtpl:39
			qw422016.N().S(row.Label)
//line mail.qtpl:39
			qw422016.N().S(`: `)
//line mail.qtpl:39
			qw422016.N().S(row.Value)
//line mail.qtpl:39
			qw422016.N().S(`
`)
//line mail.qtpl:40
		}
//line mail.qtpl:40
		qw422016.N().S(`
`)
//line mail.qtpl:41
	}
//line mail.qtpl:41
	qw422016.N().S(`
`)
//line mail.qtpl:42
	if d.NextStep != "" {
//line mail.qtpl:42
		qw422016.N().S(`
`)
//line mail.qtpl:43
		qw422016.N().S(d.NextStep)
//line mail.qtpl:43
		qw422016.N().S(`

`)
//line mail.qtpl:45
	}
//line mail.qtpl:45
	qw422016.N().S(`
`)
//line mail.qtpl:46
	qw422016.N().S(d.Footnote)
//line mail.qtpl:46
	qw422016.N().S(`
`)
//line mail.qtpl:47
}

//line mail.qtpl:47
func WriteApprovalText(qq422016 qtio422016.Writer, d ApprovalData) {
//line mail.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mail.qtpl:47
	StreamApprovalText(qw422016, d)
//line mail.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line mail.qtpl:47
}

//line mail.qtpl:47
func ApprovalText(d ApprovalData) string {
//line mail.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line mail.qtpl:47
	WriteApprovalText(qb422016, d)
//line mail.qtpl:47
	qs422016 := string(qb422016.B)
//line mail.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line mail.qtpl:47
	return qs422016
//line mail.qtpl:47
}

//line mail.qtpl:49
func StreamApprovalHTML(qw422016 *qt422016.Writer, d ApprovalData) {
//line mail.qtpl:49
	qw422016.N().S(`<!doctype html>
<html>
<body style="margin:0;padding:0;background:#f6f7fb;color:#111827;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:32px 20px;">
    <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;padding:28px;">
      <div style="font-size:13px;font-weight:700;color:#2563eb;margin-bottom:12px;">`)
//line mail.qtpl:54
	qw422016.E().S(d.AppName)
//line mail.qtpl:54
	qw422016.N().S(`</div>
      <h1 style="font-size:22px;line-height:1.3;margin:0 0 14px;color:#111827;">`)
//line mail.qtpl:55
	qw422016.E().S(d.Title)
//line mail.qtpl:55
	qw422016.N().S(`</h1>
      <p style="font-size:15px;line-height:1.7;margin:0 0 18px;color:#374151;">`)
//line mail.qtpl:56
	qw422016.E().S(d.Greeting)
//line mail.qtpl:56
	qw422016.N().S(`<br>`)
//line mail.qtpl:56
	qw422016.E().S(d.Intro)
//line mail.qtpl:56
	qw422016.N().S(`</p>
      <table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;border-top:1px solid #eef0f4;border-bottom:1px solid #eef0f4;margin:0 0 22px;">
        `)
//line mail.qtpl:58
	StreamApprovalRows(qw422016, d.Rows)
//line mail.qtpl:58
	qw422016.N().S(`
      </table>
      <p style="margin:0 0 22px;"><a href="`)
//line mail.qtpl:60
	qw422016.E().S(d.ButtonURL)
//line mail.qtpl:60
	qw422016.N().S(`" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;border-radius:6px;padding:12px 18px;font-weight:700;">`)
//line mail.qtpl:60
	qw422016.E().S(d.ButtonText)
//line mail.qtpl:60
	qw422016.N().S(`</a></p>
      <p style="font-size:12px;line-height:1.7;margin:0;color:#6b7280;">`)
//line mail.qtpl:61
	qw422016.E().S(d.Footnote)
//line mail.qtpl:61
	qw422016.N().S(`</p>
    </div>
  </div>
</body>
</html>
`)
//line mail.qtpl:66
}

//line mail.qtpl:66
func WriteApprovalHTML(qq422016 qtio422016.Writer, d ApprovalData) {
//line mail.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mail.qtpl:66
	StreamApprovalHTML(qw422016, d)
//line mail.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line mail.qtpl:66
}

//line mail.qtpl:66
func ApprovalHTML(d ApprovalData) string {
//line mail.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line mail.qtpl:66
	WriteApprovalHTML(qb422016, d)
//line mail.qtpl:66
	qs422016 := string(qb422016.B)
//line mail.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line mail.qtpl:66
	return qs422016
//line mail.qtpl:66
}

//line mail.qtpl:68
func StreamApprovalRows(qw422016 *qt422016.Writer, rows []InfoRow) {
//line mail.qtpl:68
	for _, row := range rows {
//line mail.qtpl:68
		qw422016.N().S(`
`)
//line mail.qtpl:69
		if row.Value != "" {
//line mail.qtpl:69
			qw422016.N().S(`
<tr><td style="padding:8px 0;color:#6b7280;font-size:13px;vertical-align:top;width:96px;">`)
//line mail.qtpl:70
			qw422016.E().S(row.Label)
//line mail.qtpl:70
			qw422016.N().S(`</td><td style="padding:8px 0;color:#111827;font-size:14px;line-height:1.6;word-break:break-word;">`)
//line mail.qtpl:70
			qw422016.E().S(row.Value)
//line mail.qtpl:70
			qw422016.N().S(`</td></tr>
`)
//line mail.qtpl:71
		}
//line mail.qtpl:71
		qw422016.N().S(`
`)
//line mail.qtpl:72
	}
//line mail.qtpl:72
	qw422016.N().S(`
`)
//line mail.qtpl:73
}

//line mail.qtpl:73
func WriteApprovalRows(qq422016 qtio422016.Writer, rows []InfoRow) {
//line mail.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mail.qtpl:73
	StreamApprovalRows(qw422016, rows)
//line mail.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line mail.qtpl:73
}

//line mail.qtpl:73
func ApprovalRows(rows []InfoRow) string {
//line mail.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
//line mail.qtpl:73
	WriteApprovalRows(qb422016, rows)
//line mail.qtpl:73
	qs422016 := string(qb422016.B)
//line mail.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
//line mail.qtpl:73
	return qs422016
//line mail.qtpl:73
}
